
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendations-v2
  template:
    metadata:
      labels:
        app: recommendations-v2
    spec:
      containers:
        - name: recommendations-v2
          image: ghcr.io/f5devcentral/spa-demo-app-recommendations:sha-8123c6f
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: recommendations-v2
spec:
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: recommendations-v2
