apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: brewz
spec:
  host: brewz.f5demo.com
  tls:
    secret: brewz-tls
  upstreams:
    - name: spa
      service: spa
      port: 80
    - name: api
      service: api
      port: 8000
      healthCheck:
        enable: true
        path: /api/stats
        interval: 20s
        jitter: 3s
        port: 8000
    - name: recommendations-v2
      service: recommendations-v2
      port: 8001
  routes:
    - path: /
      action:
        pass: spa
    - path: /api
      action:
        pass: api
      errorPages:
        - codes: [404]
          return:
            code: 404
            type: application/json
            body: |
              {\"msg\": \"Could not find the product!\"}
            headers:
            - name: x-debug-original-status
              value: ${upstream_status}
    - path: /images
      action:
        proxy:
          upstream: api
          rewritePath: /images
